services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - spark-network

  kafka:
    image: bitnami/kafka:3.5
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9094,EXTERNAL://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9094,EXTERNAL://0.0.0.0:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - spark-network

  scylla:
    image: scylladb/scylla:latest
    container_name: scylla
    restart: always
    ports:
      - "9042:9042"
    environment:
      - SCYLLA_USER=scylla
      - SCYLLA_PASSWORD=scylla
    volumes:
      - scylla-data:/var/lib/scylla
    networks:
      - spark-network

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app
    command: sleep infinity
    restart: always
    networks:
      - spark-network

volumes:
  scylla-data:
    driver: local

networks:
  spark-network:
    driver: bridge
    